const actions = {
  SET_APP_TO_INITIAL_STATE: 'SET_APP_TO_INITIAL_STATE',
  SET_ADDRESS: 'SET_ADDRESS',
  SET_PROFILE: 'SET_PROFILE',
  SET_SUBSCRIPTIONS: 'SET_SUBSCRIPTIONS'
}

export default actions
